# Generated by Django 3.2.6 on 2022-10-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Выберите статус аккаунта', verbose_name='Статус аккаунта'),
        ),
    ]
